const { Pets } = require('../models');

const petData = [
  {
    pet_name: 'Jameson',
    color: 'Brindle',
    species: 'Dog',
    age: 1,
    size: 'Medium',
    potty_trained: true,
    vaccinated: 1,
    microchip: 1,
    description: 'Energetic pup that loves hiking!',
    user_id: 1,
  },
  {
    pet_name: 'Karen',
    color: 'Brown',
    species: 'Dog',
    age: 4,
    size: 'Large',
    potty_trained: true,
    vaccinated: 1,
    microchip: 0,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu condimentum lacus. Pellentesque accumsan gravida interdum.',
    user_id: 1,
  },
  {
    pet_name: 'Jerry',
    color: 'Black',
    species: 'Dog',
    age: 6,
    size: 'Small',
    potty_trained: true,
    vaccinated: false,
    microchip: 0,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero ex, sagittis quis ipsum et, suscipit condimentum tortor.',
    user_id: 1,
  },
  {
    pet_name: 'Larry',
    color: 'Multi-color',
    species: 'Dog',
    age: 10,
    size: 'Medium',
    potty_trained: false,
    vaccinated: false,
    microchip: 0,
    description: 'Aliquam erat volutpat. Pellentesque libero neque, placerat quis blandit convallis, pretium eu justo. Sed',
    user_id: 2,
  },
  {
    pet_name: 'Fluffy',
    color: 'White',
    species: 'Cat',
    age: 1,
    size: 'Small',
    potty_trained: false,
    vaccinated: 1,
    microchip: 1,
    description: 'Cuddly kitten that loves soft blankets',
    user_id: 2,
  },
  {
    pet_name: 'Titus',
    color: 'Black',
    species: 'Dog',
    age: 7,
    size: 'Large',
    potty_trained:0,
    vaccinated: 1,
    microchip: 0,
    description: 'Independent and protective husky mix',
    user_id: 3,
  },
  {
    pet_name: 'Sophie',
    color: 'Grey',
    species: 'Cat',
    age: 2,
    size: 'Small',
    potty_trained:1,
    vaccinated: 1,
    microchip: 1,
    description: 'Shy at first but very playful and cuddly once she warms up!',
    user_id: 4,
  },
  {
    pet_name: 'Tyro',
    color: 'Tan/Black',
    species: 'Dog',
    age: 15,
    size: 'Small',
    potty_trained:0,
    vaccinated: 1,
    microchip: 0,
    description: 'Purebreed Yorkie that loves to nap but can also go on long walks',
    user_id: 5,
  },
  {
    pet_name: 'Sunshine',
    color: 'Orange',
    species: 'Cat',
    age: 9,
    size: 'Medium',
   potty_trained: true,
    vaccinated: false,
    microchip: 0,
    description: 'Very independent cat that loves treats',
    user_id: 6,
  },
  {
    pet_name: 'River',
    color: 'Tri-color',
    species: 'Dog',
    age: 3,
    size: 'Medium',
    potty_trained: true,
    vaccinated: true,
    microchip: false,
    description: 'Beagle/Coonhound mix that is very playful. Loves walks and new smells.',
    user_id: 4,
  },
  {
    pet_name: 'Ginger',
    color: 'Tortoiseshell',
    species: 'Cat',
    age: 5,
    size: 'Large',
    potty_trained: false,
    vaccinated: 1,
    microchip: 1,
    description: 'Loves being outdoors.',
    user_id: 3,
  }
];



const seedPets = () => Pets.bulkCreate(petData);

module.exports = seedPets;